name: Extract backup
on:
  schedule:
    - cron: "45 */1 * * *"
  workflow_dispatch:

env:
  FILE_URL: "https://hin.isherv.in/"
  OUTPUT_FILE: "backup.txt"
  BASE64_FILE: "backup_B64.txt"
  CLASH_YAML_FILE: "backup_clash.yaml"
  
jobs:
  extract_configs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Git Config
        run: |
          git config --global user.name "${{ secrets.GIT_USERNAME }}"
          git config --global user.email "${{ secrets.GIT_EMAIL }}"

      - name: Download TXT File
        run: |
          curl -o temp64.txt -L "${FILE_URL}"

      - name: Extract Lines Starting with "vmess://" and "vless://"
        run: |
          grep -E '^vless://|^vmess://' temp64.txt > "${GITHUB_WORKSPACE}/${OUTPUT_FILE}"

      - name: Replace Tag in V2Ray URLs
        run: |
          sed -i 's/#.*/#Provided%20by%20%E2%9D%8CSS-Collector%E2%9D%8C/' "${GITHUB_WORKSPACE}/${OUTPUT_FILE}"

      - name: Convert Lines to Base64 and Save
        run: |
          cat "${GITHUB_WORKSPACE}/${OUTPUT_FILE}" | base64 -w 0 > "${GITHUB_WORKSPACE}/${BASE64_FILE}"

      - name: Fetch Content and Generate YAML
        run: |
          curl -o "${GITHUB_WORKSPACE}/${CLASH_YAML_FILE}" -L "https://yebekhe.serv00.net/api/clash/?url=https://hin.isherv.in/&type=meta&process=full"
         
          # Optional: Convert to YAML format if needed
          # cat "${GITHUB_WORKSPACE}/${CLASH_YAML_FILE}" | yq eval -j - > "${GITHUB_WORKSPACE}/${CLASH_YAML_FILE}"

      - name: Clean Up
        run: |
          rm temp64.txt

      - name: Commit and Push Changes
        run: |
          git add "${GITHUB_WORKSPACE}/${OUTPUT_FILE}" "${GITHUB_WORKSPACE}/${BASE64_FILE}" "${GITHUB_WORKSPACE}/${CLASH_YAML_FILE}"
          git commit -m "Update backup.txt, backup_B64.txt, backup_clash.yaml" || true
          git remote remove origin
          git remote add origin "https://github.com/lagzian/SS-Collector.git"
          git push origin HEAD:${GITHUB_REF}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN1 }}
