name: Extract Shadowsocks 

on:
  workflow_dispatch:  
  schedule:
    - cron: "0 */12 * * *"

jobs:

  extract:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Delete existing file
      run: |
        rm -f shadowsockes.txt
        
    - name: Download and extract
      run: |
        curl https://raw.githubusercontent.com/mahdibland/ShadowsocksAggregator/master/Eternity.txt | grep '^ss://' > shadowsockes.txt

    - name: Commit changes
      run: |
        git config --global user.name 'Automated'
        git config --global user.email 'actions@users.noreply.github.com'
        git add .
        git commit -m "Extracted shadowsocks"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with: 
        github_token: ${{ secrets.ACCESS_TOKEN }}
