name: Extract Shadowsocks
on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

env:
  FILE_URL: "https://raw.githubusercontent.com/mahdibland/ShadowsocksAggregator/master/Eternity.txt"
  OUTPUT_FILE: "shadowsockes.txt"
  GIT_USERNAME: "lagzian"
  GIT_EMAIL: "milad.lagzian@gmail.com"

jobs:
  extract_shadowsocks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Git Config
        run: |
          git config --global user.name "${GIT_USERNAME}"
          git config --global user.email "${GIT_EMAIL}"

      - name: Download TXT File
        run: |
          curl -o temp.txt -L "${FILE_URL}"

      - name: Extract Lines Starting with "ss://"
        run: |
          grep '^ss://' temp.txt > "${GITHUB_WORKSPACE}/${OUTPUT_FILE}"

      - name: Clean Up
        run: |
          rm temp.txt

      - name: Commit and Push Changes
        run: |
          git add "${GITHUB_WORKSPACE}/${OUTPUT_FILE}"
          git commit -m "Update shadowsockes.txt" || true
          git remote remove origin
          git remote add origin "https://github.com/lagzian/SS-Collector.git"
          git push origin HEAD:${GITHUB_REF}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN1 }}
