name: SS_final2
on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

env:
  FILE_URL: "https://raw.githubusercontent.com/mahdibland/ShadowsocksAggregator/master/Eternity.txt"
  OUTPUT_FILE: "shadowsockes.txt"
  BASE64_FILE: "SS_B64.txt"
  CLASH_YAML_FILE: "ss_clash.yaml"

jobs:
  extract_shadowsocks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Git Config
        run: |
          git config --global user.name "${{ secrets.GIT_USERNAME }}"
          git config --global user.email "${{ secrets.GIT_EMAIL }}"

      - name: Download TXT File
        run: |
          curl -o temp.txt -L "${FILE_URL}"
        continue-on-error: false

      - name: Commit and Push TXT File
        run: |
          git add "${GITHUB_WORKSPACE}/temp.txt"
          git commit -m "Add temp.txt"
          git remote remove origin
          git remote add origin "https://github.com/lagzian/SS-Collector.git"
          git push origin HEAD:${GITHUB_REF}
        continue-on-error: false

      - name: Extract Lines Starting with "ss://"
        run: |
          grep '^ss://' temp.txt > "${GITHUB_WORKSPACE}/${OUTPUT_FILE}"
        continue-on-error: false

      - name: Commit and Push Output File
        run: |
          git add "${GITHUB_WORKSPACE}/${OUTPUT_FILE}"
          git commit -m "Add shadowsockes.txt"
          git push origin HEAD:${GITHUB_REF}
        continue-on-error: false

      - name: Convert Lines to Base64 and Save
        run: |
          cat "${GITHUB_WORKSPACE}/${OUTPUT_FILE}" | base64 -w 0 > "${GITHUB_WORKSPACE}/${BASE64_FILE}"
        continue-on-error: false

      - name: Commit and Push Base64 File
        run: |
          git add "${GITHUB_WORKSPACE}/${BASE64_FILE}"
          git commit -m "Add SS_B64.txt"
          git push origin HEAD:${GITHUB_REF}
        continue-on-error: false

      - name: Fetch Content and Generate YAML
        run: |
          curl -o "${GITHUB_WORKSPACE}/${CLASH_YAML_FILE}" -L "https://pub-api-1.bianyuan.xyz/sub?target=clash&url=https%3A%2F%2Fraw.githubusercontent.com%2Flagzian%2FSS-Collector%2Fmain%2FSS_B64.txt&insert=false&emoji=true&list=false&tfo=false&scv=false&fdn=false&sort=false&new_name=true"
          # Optional: Convert to YAML format if needed
          # cat "${GITHUB_WORKSPACE}/${CLASH_YAML_FILE}" | yq eval -j - > "${GITHUB_WORKSPACE}/${CLASH_YAML_FILE}"
        continue-on-error: false

      - name: Commit and Push YAML File
        run: |
          git add "${GITHUB_WORKSPACE}/${CLASH_YAML_FILE}"
          git commit -m "Add ss_clash.yaml"
          git push origin HEAD:${GITHUB_REF}
        continue-on-error: false

      - name: Clean Up
        run: |
          rm "${GITHUB_WORKSPACE}/temp.txt"

      - name: Finalize Workflow
        run: |
          echo "Workflow completed."
