name: Extract Reality
on:
  schedule:
    - cron: "0 */1 * * *"
  workflow_dispatch:

env:
  FILE_URL: "https://raw.githubusercontent.com/lagzian/TelegramV2rayCollector/main/sub/normal/reality"
  OUTPUT_FILE: "reality.txt"
  BASE64_FILE: "reality_B64.txt"
  CLASH_YAML_FILE: "reality_clash.yaml"

jobs:
  extract_shadowsocks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Git Config
        run: |
          git config --global user.name "${{ secrets.GIT_USERNAME }}"
          git config --global user.email "${{ secrets.GIT_EMAIL }}"

      - name: Download TXT File
        run: |
          curl -o temp2.txt -L "${FILE_URL}"

      - name: Extract Lines Starting with "vless://"
        run: |
          grep '^vless://' temp2.txt > "${GITHUB_WORKSPACE}/${OUTPUT_FILE}"

      - name: Convert Lines to Base64 and Save
        run: |
          cat "${GITHUB_WORKSPACE}/${OUTPUT_FILE}" | base64 -w 0 > "${GITHUB_WORKSPACE}/${BASE64_FILE}"

      - name: Fetch Content and Generate YAML
        run: |
          curl -o "${GITHUB_WORKSPACE}/${CLASH_YAML_FILE}" -L "https://api.yebekhe.link/toClash/?url=https%3A%2F%2Fraw.githubusercontent.com%2Flagzian%2FSS-Collector%2Fmain%2Freality_B64.txt&type=meta&process=full"
          # Optional: Convert to YAML format if needed
          # cat "${GITHUB_WORKSPACE}/${CLASH_YAML_FILE}" | yq eval -j - > "${GITHUB_WORKSPACE}/${CLASH_YAML_FILE}"

      - name: Clean Up
        run: |
          rm temp2.txt

      - name: Commit and Push Changes
        run: |
          git add "${GITHUB_WORKSPACE}/${OUTPUT_FILE}" "${GITHUB_WORKSPACE}/${BASE64_FILE}" "${GITHUB_WORKSPACE}/${CLASH_YAML_FILE}"
          git commit -m "Update reality.txt, reality_B64.txt, and reality_clash.yaml" || true
          git remote remove origin
          git remote add origin "https://github.com/lagzian/SS-Collector.git"
          git push origin HEAD:${GITHUB_REF}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN1 }}
