name: Speed Test

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */5 * * *"

jobs:
  main:
    name: SpeedTest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Set Timezone
        run: sudo timedatectl set-timezone 'Asia/Tehran'

      - name: Upgrade setuptools and wheel
        run: |
          python -m pip install --upgrade setuptools wheel

      - name: Install libyaml
        run: sudo apt-get install libyaml-dev

      - name: Install Requirements
        run: |
          pip install -r ./utils/requirements.txt

      - name: Run Lite Speedtest
        run: |
          sleep 5
          sudo sh ./utils/speedtest/speedtest2.sh
          python ./utils/speedtest/output.py
      

      - name: Commit Changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git pull origin main
          git add ./SS/TrinityBase
          git add ./SS/Trinity
          git add ./SS/Trinity.txt
          git add LogInfo.txt
          git checkout main
          git commit -m "✔️ $(date '+%Y-%m-%d %H:%M:%S') Speed Test"

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          branch: main
