name: Import VLESS Configs
on:
  schedule:
    - cron: "*/50 * * * *"  # Runs every 50 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  import-configs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Set up environment
        run: |
          mkdir -p ./VLESS
          
      - name: Download and Process VLESS Configs
        run: |
          # Download B64 configs
          curl -sSL "https://raw.githubusercontent.com/lagzian/new-configs-collector/main/protocols/vless" -o temp_b64.txt
          
          # Decode B64 to temporary file
          cat temp_b64.txt | base64 -d > temp_decoded.txt
          
          # Remove first and last lines and save to final file
          sed '1d;$d' temp_decoded.txt > ./VLESS/vless_vip.txt
          
          # Select 100 random configs from different centuries and save to VL100.txt
          awk '
          BEGIN { srand() }
          {
            century = substr($0, length($0)-4, 2)  # Extract country code
            if (!(century in seen) || rand() < count[century]/seen[century]) {
              if (count[century] < 10) {  # Limit to ~10 configs per country
                selected[NR] = $0
                count[century]++
              }
            }
            seen[century]++
          }
          END {
            # Print random selection, limit to 100
            n = asort(selected)
            limit = (n < 100) ? n : 100
            for (i = 1; i <= limit; i++) {
              print selected[i]
            }
          }' ./VLESS/vless_vip.txt | shuf -n 100 > ./VLESS/VL100.txt
          
          # Clean up temporary files
          rm temp_b64.txt temp_decoded.txt
          
      - name: Check for Changes
        id: check_changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Commit and Push Changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add ./VLESS/vless_vip.txt ./VLESS/VL100.txt
          git commit -m "Update VLESS configs"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Error Check
        run: |
          if [ ! -f ./VLESS/vless_vip.txt ] || [ ! -f ./VLESS/VL100.txt ]; then
            echo "Error: One or more config files were not created!"
            exit 1
          fi
          if [ ! -s ./VLESS/vless_vip.txt ] || [ ! -s ./VLESS/VL100.txt ]; then
            echo "Warning: One or more config files are empty!"
          fi
          
          # Display number of configs
          echo "Number of configs in vless_vip.txt: $(wc -l < ./VLESS/vless_vip.txt)"
          echo "Number of configs in VL100.txt: $(wc -l < ./VLESS/VL100.txt)"
